# Generated by Django 4.2.5 on 2023-09-24 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='connection_status',
        ),
    ]
